export enum SackItem {
    "WHEAT" = "WHEAT",
    "CARROT" = "CARROT",
    "POTATO" = "POTATO",
    "PUMPKIN" = "PUMPKIN",
    "MELON" = "MELON",
    "SEEDS" = "SEEDS",
    "MUSHROOM" = "MUSHROOM",
    "COCOA_BEANS" = "COCOA_BEANS",
    "CACTUS" = "CACTUS",
    "SUGAR_CANE" = "SUGAR_CANE",
    "NETHER_WART" = "NETHER_WART",
    "FEATHER" = "FEATHER",
    "LEATHER" = "LEATHER",
    "RAW_PORKCHOP" = "RAW_PORKCHOP",
    "RAW_CHICKEN" = "RAW_CHICKEN",
    "MUTTON" = "MUTTON",
    "RAW_RABBIT" = "RAW_RABBIT",
    "COBBLESTONE" = "COBBLESTONE",
    "COAL" = "COAL",
    "IRON_INGOT" = "IRON_INGOT",
    "GOLD_INGOT" = "GOLD_INGOT",
    "DIAMOND" = "DIAMOND",
    "LAPIS_LAZULI" = "LAPIS_LAZULI",
    "EMERALD" = "EMERALD",
    "REDSTONE" = "REDSTONE",
    "NETHER_QUARTZ" = "NETHER_QUARTZ",
    "OBSIDIAN" = "OBSIDIAN",
    "GLOWSTONE_DUST" = "GLOWSTONE_DUST",
    "GRAVEL" = "GRAVEL",
    "ICE" = "ICE",
    "NETHERRACK" = "NETHERRACK",
    "SAND" = "SAND",
    "END_STONE" = "END_STONE",
    "MITHRIL" = "MITHRIL",
    "TITANIUM" = "TITANIUM",
    "TREASURITE" = "TREASURITE",
    "STARFALL" = "STARFALL",
    "HARD_STONE" = "HARD_STONE",
    "ROTTEN_FLESH" = "ROTTEN_FLESH",
    "BONE" = "BONE",
    "STRING" = "STRING",
    "SPIDER_EYE" = "SPIDER_EYE",
    "GUNPOWDER" = "GUNPOWDER",
    "ENDER_PEARL" = "ENDER_PEARL",
    "GHAST_TEAR" = "GHAST_TEAR",
    "SLIMEBALL" = "SLIMEBALL",
    "BLAZE_ROD" = "BLAZE_ROD",
    "MAGMA_CREAM" = "MAGMA_CREAM",
    "OAK_WOOD" = "OAK_WOOD",
    "SPRUCE_WOOD" = "SPRUCE_WOOD",
    "BIRCH_WOOD" = "BIRCH_WOOD",
    "DARK_OAK_WOOD" = "DARK_OAK_WOOD",
    "ACACIA_WOOD" = "ACACIA_WOOD",
    "JUNGLE_WOOD" = "JUNGLE_WOOD",
    "APPLE" = "APPLE",
    "OAK_SAPLING" = "OAK_SAPLING",
    "BIRCH_SAPLING" = "BIRCH_SAPLING",
    "SPRUCE_SAPLING" = "SPRUCE_SAPLING",
    "ACACIA_SAPLING" = "ACACIA_SAPLING",
    "DARK_OAK_SAPLING" = "DARK_OAK_SAPLING",
    "JUNGLE_SAPLING" = "JUNGLE_SAPLING",
    "RAW_FISH" = "RAW_FISH",
    "RAW_SALMON" = "RAW_SALMON",
    "CLOWNFISH" = "CLOWNFISH",
    "PUFFERFISH" = "PUFFERFISH",
    "PRISMARINE_SHARD" = "PRISMARINE_SHARD",
    "PRISMARINE_CRYSTALS" = "PRISMARINE_CRYSTALS",
    "CLAY" = "CLAY",
    "LILY_PAD" = "LILY_PAD",
    "INK_SACK" = "INK_SACK",
    "SPONGE" = "SPONGE",
    "ROUGH_RUBY_GEMSTONE" = "ROUGH_RUBY_GEMSTONE",
    "FLAWED_RUBY_GEMSTONE" = "FLAWED_RUBY_GEMSTONE",
    "FINE_RUBY_GEMSTONE" = "FINE_RUBY_GEMSTONE",
    "FLAWLESS_RUBY_GEMSTONE" = "FLAWLESS_RUBY_GEMSTONE",
    "ROUGH_AMBER_GEMSTONE" = "ROUGH_AMBER_GEMSTONE",
    "FLAWED_AMBER_GEMSTONE" = "FLAWED_AMBER_GEMSTONE",
    "FINE_AMBER_GEMSTONE" = "FINE_AMBER_GEMSTONE",
    "FLAWLESS_AMBER_GEMSTONE" = "FLAWLESS_AMBER_GEMSTONE",
    "ROUGH_SAPPHIRE_GEMSTONE" = "ROUGH_SAPPHIRE_GEMSTONE",
    "FLAWED_SAPPHIRE_GEMSTONE" = "FLAWED_SAPPHIRE_GEMSTONE",
    "FINE_SAPPHIRE_GEMSTONE" = "FINE_SAPPHIRE_GEMSTONE",
    "FLAWLESS_SAPPHIRE_GEMSTONE" = "FLAWLESS_SAPPHIRE_GEMSTONE",
    "ROUGH_JADE_GEMSTONE" = "ROUGH_JADE_GEMSTONE",
    "FLAWED_JADE_GEMSTONE" = "FLAWED_JADE_GEMSTONE",
    "FINE_JADE_GEMSTONE" = "FINE_JADE_GEMSTONE",
    "FLAWLESS_JADE_GEMSTONE" = "FLAWLESS_JADE_GEMSTONE",
    "ROUGH_AMETHYST_GEMSTONE" = "ROUGH_AMETHYST_GEMSTONE",
    "FLAWED_AMETHYST_GEMSTONE" = "FLAWED_AMETHYST_GEMSTONE",
    "FINE_AMETHYST_GEMSTONE" = "FINE_AMETHYST_GEMSTONE",
    "FLAWLESS_AMETHYST_GEMSTONE" = "FLAWLESS_AMETHYST_GEMSTONE",
    "ROUGH_TOPAZ_GEMSTONE" = "ROUGH_TOPAZ_GEMSTONE",
    "FLAWED_TOPAZ_GEMSTONE" = "FLAWED_TOPAZ_GEMSTONE",
    "FINE_TOPAZ_GEMSTONE" = "FINE_TOPAZ_GEMSTONE",
    "FLAWLESS_TOPAZ_GEMSTONE" = "FLAWLESS_TOPAZ_GEMSTONE",
    "ROUGH_JASPER_GEMSTONE" = "ROUGH_JASPER_GEMSTONE",
    "FLAWED_JASPER_GEMSTONE" = "FLAWED_JASPER_GEMSTONE",
    "FINE_JASPER_GEMSTONE" = "FINE_JASPER_GEMSTONE",
    "FLAWLESS_JASPER_GEMSTONE" = "FLAWLESS_JASPER_GEMSTONE",
    "SULPHUR" = "SULPHUR",
    "RED_SAND" = "RED_SAND",
    "MYCELIUM" = "MYCELIUM",
    "SPECTRE_DUST" = "SPECTRE_DUST",
    "BLAZE_ASHES" = "BLAZE_ASHES",
    "MUTATED_BLAZE_ASHES" = "MUTATED_BLAZE_ASHES",
    "WITHER_SOUL" = "WITHER_SOUL",
    "MAGMA_CHUNK" = "MAGMA_CHUNK",
    "BEZOS" = "BEZOS",
    "BURNING_EYE" = "BURNING_EYE",
    "TENTACLE_MEAT" = "TENTACLE_MEAT",
    "DIGESTED_MUSHROOMS" = "DIGESTED_MUSHROOMS",
    "KADA_LEAD" = "KADA_LEAD",
    "MAGMAG" = "MAGMAG",
    "GAZING_PEARL" = "GAZING_PEARL",
    "LEATHER_CLOTH" = "LEATHER_CLOTH",
    "SPELL_POWDER" = "SPELL_POWDER",
    "COMPACT_OOZE" = "COMPACT_OOZE",
    "LUMINO_FIBER" = "LUMINO_FIBER",
    "HALLOWED_SKULL" = "HALLOWED_SKULL",
    "CORRUPTED_FRAGMENT" = "CORRUPTED_FRAGMENT",
    "BLAZE_POWDER" = "BLAZE_POWDER",
    "ENCHANTED_COAL" = "ENCHANTED_COAL",
    "CUP_OF_BLOOD" = "CUP_OF_BLOOD",
    "FLAMING_HEART" = "FLAMING_HEART",
    "HORN_OF_TAURUS" = "HORN_OF_TAURUS",
    "LUMP_OF_MAGMA" = "LUMP_OF_MAGMA",
    "ENCHANTED_MAGMA_CREAM" = "ENCHANTED_MAGMA_CREAM",
    "MAGMAFISH" = "MAGMAFISH",
    "MOOGMA_PELT" = "MOOGMA_PELT",
    "ENCHANTED_NETHERRACK" = "ENCHANTED_NETHERRACK",
    "ORB_OF_ENERGY" = "ORB_OF_ENERGY",
    "PYROCLASTIC_SCALE" = "PYROCLASTIC_SCALE",
    "ENCHANTED_CARROT" = "ENCHANTED_CARROT",
    "ENCHANTED_POTATO" = "ENCHANTED_POTATO",
    "ENCHANTED_PUMPKIN" = "ENCHANTED_PUMPKIN",
    "ENCHANTED_MELON" = "ENCHANTED_MELON",
    "ENCHANTED_SEEDS" = "ENCHANTED_SEEDS",
    "ENCHANTED_MUSHROOM" = "ENCHANTED_MUSHROOM",
    "ENCHANTED_COCOA_BEAN" = "ENCHANTED_COCOA_BEAN",
    "ENCHANTED_CACTUS" = "ENCHANTED_CACTUS",
    "ENCHANTED_SUGAR" = "ENCHANTED_SUGAR",
    "ENCHANTED_NETHER_WART" = "ENCHANTED_NETHER_WART",
    "ENCHANTED_BREAD" = "ENCHANTED_BREAD",
    "ENCHANTED_FEATHER" = "ENCHANTED_FEATHER",
    "ENCHANTED_LEATHER" = "ENCHANTED_LEATHER",
    "ENCHANTED_PORK" = "ENCHANTED_PORK",
    "ENCHANTED_RAW_CHICKEN" = "ENCHANTED_RAW_CHICKEN",
    "ENCHANTED_MUTTON" = "ENCHANTED_MUTTON",
    "ENCHANTED_RAW_RABBIT" = "ENCHANTED_RAW_RABBIT",
    "ENCHANTED_COBBLESTONE" = "ENCHANTED_COBBLESTONE",
    "ENCHANTED_IRON" = "ENCHANTED_IRON",
    "ENCHANTED_GOLD" = "ENCHANTED_GOLD",
    "ENCHANTED_DIAMOND" = "ENCHANTED_DIAMOND",
    "ENCHANTED_LAPIS_LAZULI" = "ENCHANTED_LAPIS_LAZULI",
    "ENCHANTED_EMERALD" = "ENCHANTED_EMERALD",
    "ENCHANTED_REDSTONE" = "ENCHANTED_REDSTONE",
    "ENCHANTED_QUARTZ" = "ENCHANTED_QUARTZ",
    "ENCHANTED_OBSIDIAN" = "ENCHANTED_OBSIDIAN",
    "ENCHANTED_GLOWSTONE_DUST" = "ENCHANTED_GLOWSTONE_DUST",
    "ENCHANTED_FLINT" = "ENCHANTED_FLINT",
    "ENCHANTED_ICE" = "ENCHANTED_ICE",
    "ENCHANTED_SAND" = "ENCHANTED_SAND",
    "ENCHANTED_END_STONE" = "ENCHANTED_END_STONE",
    "ENCHANTED_MITHRIL" = "ENCHANTED_MITHRIL",
    "ENCHANTED_TITANIUM" = "ENCHANTED_TITANIUM",
    "ENCHANTED_ROTTEN_FLESH" = "ENCHANTED_ROTTEN_FLESH",
    "ENCHANTED_BONE" = "ENCHANTED_BONE",
    "ENCHANTED_STRING" = "ENCHANTED_STRING",
    "ENCHANTED_SPIDER_EYE" = "ENCHANTED_SPIDER_EYE",
    "ENCHANTED_GUNPOWDER" = "ENCHANTED_GUNPOWDER",
    "ENCHANTED_ENDER_PEARL" = "ENCHANTED_ENDER_PEARL",
    "ENCHANTED_GHAST_TEAR" = "ENCHANTED_GHAST_TEAR",
    "ENCHANTED_SLIMEBALL" = "ENCHANTED_SLIMEBALL",
    "ENCHANTED_BLAZE_POWDER" = "ENCHANTED_BLAZE_POWDER",
    "ENCHANTED_OAK_WOOD" = "ENCHANTED_OAK_WOOD",
    "ENCHANTED_SPRUCE_WOOD" = "ENCHANTED_SPRUCE_WOOD",
    "ENCHANTED_BIRCH_WOOD" = "ENCHANTED_BIRCH_WOOD",
    "ENCHANTED_DARK_OAK_WOOD" = "ENCHANTED_DARK_OAK_WOOD",
    "ENCHANTED_ACACIA_WOOD" = "ENCHANTED_ACACIA_WOOD",
    "ENCHANTED_JUNGLE_WOOD" = "ENCHANTED_JUNGLE_WOOD",
    "ENCHANTED_RAW_FISH" = "ENCHANTED_RAW_FISH",
    "ENCHANTED_RAW_SALMON" = "ENCHANTED_RAW_SALMON",
    "ENCHANTED_CLOWNFISH" = "ENCHANTED_CLOWNFISH",
    "ENCHANTED_PUFFERFISH" = "ENCHANTED_PUFFERFISH",
    "ENCHANTED_PRISMARINE_SHARD" = "ENCHANTED_PRISMARINE_SHARD",
    "ENCHANTED_PRISMARINE_CRYSTALS" = "ENCHANTED_PRISMARINE_CRYSTALS",
    "ENCHANTED_CLAY" = "ENCHANTED_CLAY",
    "ENCHANTED_LILY_PAD" = "ENCHANTED_LILY_PAD",
    "ENCHANTED_INK_SACK" = "ENCHANTED_INK_SACK",
    "ENCHANTED_SPONGE" = "ENCHANTED_SPONGE",
    "REVENANT_FLESH" = "REVENANT_FLESH",
    "UNDEAD_CATALYST" = "UNDEAD_CATALYST",
    "REVENANT_CATALYST" = "REVENANT_CATALYST",
    "TARANTULA_WEB" = "TARANTULA_WEB",
    "SPIDER_CATALYST" = "SPIDER_CATALYST",
    "WOLF_TOOTH" = "WOLF_TOOTH",
    "NULL_SPHERE" = "NULL_SPHERE",
    "RAW_SOULFLOW" = "RAW_SOULFLOW",
    "SOULFLOW" = "SOULFLOW",
    "NULL_ATOM" = "NULL_ATOM",
    "DERELICT_ASHE" = "DERELICT_ASHE",
    "CRUDE_GABAGOOL" = "CRUDE_GABAGOOL",
    "SPIRIT_LEAP" = "SPIRIT_LEAP",
    "TRAP" = "TRAP",
    "INFLATABLE_JERRY" = "INFLATABLE_JERRY",
    "DECOY" = "DECOY",
    "GREEN_CANDY" = "GREEN_CANDY",
    "PURPLE_CANDY" = "PURPLE_CANDY",
    "PUMPKIN_GUTS" = "PUMPKIN_GUTS",
    "ECTOPLASM" = "ECTOPLASM",
    "WEREWOLF_SKIN" = "WEREWOLF_SKIN",
    "WHITE_GIFT" = "WHITE_GIFT",
    "GREEN_GIFT" = "GREEN_GIFT",
    "RED_GIFT" = "RED_GIFT",
    "ENCHANTED_SNOW_BLOCK" = "ENCHANTED_SNOW_BLOCK",
    "SNOWBALL" = "SNOWBALL",
    "ENCHANTED_PACKED_ICE" = "ENCHANTED_PACKED_ICE",
    "HUNK_OF_ICE" = "HUNK_OF_ICE",
    "HUNK_OF_BLUE_ICE" = "HUNK_OF_BLUE_ICE"
}

export interface SacksCounts {
    [SackItem.ACACIA_SAPLING]?: number;
    [SackItem.ACACIA_WOOD]?: number;
    [SackItem.APPLE]?: number;
    [SackItem.BEZOS]?: number;
    [SackItem.BIRCH_SAPLING]?: number;
    [SackItem.BIRCH_WOOD]?: number;
    [SackItem.BLAZE_ASHES]?: number;
    [SackItem.BLAZE_POWDER]?: number;
    [SackItem.BLAZE_ROD]?: number;
    [SackItem.BONE]?: number;
    [SackItem.BURNING_EYE]?: number;
    [SackItem.CACTUS]?: number;
    [SackItem.CARROT]?: number;
    [SackItem.CLAY]?: number;
    [SackItem.CLOWNFISH]?: number;
    [SackItem.COAL]?: number;
    [SackItem.COBBLESTONE]?: number;
    [SackItem.COCOA_BEANS]?: number;
    [SackItem.COMPACT_OOZE]?: number;
    [SackItem.CORRUPTED_FRAGMENT]?: number;
    [SackItem.CRUDE_GABAGOOL]?: number;
    [SackItem.CUP_OF_BLOOD]?: number;
    [SackItem.DARK_OAK_SAPLING]?: number;
    [SackItem.DARK_OAK_WOOD]?: number;
    [SackItem.DECOY]?: number;
    [SackItem.DERELICT_ASHE]?: number;
    [SackItem.DIAMOND]?: number;
    [SackItem.DIGESTED_MUSHROOMS]?: number;
    [SackItem.ECTOPLASM]?: number;
    [SackItem.EMERALD]?: number;
    [SackItem.ENCHANTED_ACACIA_WOOD]?: number;
    [SackItem.ENCHANTED_BIRCH_WOOD]?: number;
    [SackItem.ENCHANTED_BLAZE_POWDER]?: number;
    [SackItem.ENCHANTED_BONE]?: number;
    [SackItem.ENCHANTED_BREAD]?: number;
    [SackItem.ENCHANTED_CACTUS]?: number;
    [SackItem.ENCHANTED_CARROT]?: number;
    [SackItem.ENCHANTED_CLAY]?: number;
    [SackItem.ENCHANTED_CLOWNFISH]?: number;
    [SackItem.ENCHANTED_COAL]?: number;
    [SackItem.ENCHANTED_COBBLESTONE]?: number;
    [SackItem.ENCHANTED_COCOA_BEAN]?: number;
    [SackItem.ENCHANTED_DARK_OAK_WOOD]?: number;
    [SackItem.ENCHANTED_DIAMOND]?: number;
    [SackItem.ENCHANTED_EMERALD]?: number;
    [SackItem.ENCHANTED_ENDER_PEARL]?: number;
    [SackItem.ENCHANTED_END_STONE]?: number;
    [SackItem.ENCHANTED_FEATHER]?: number;
    [SackItem.ENCHANTED_FLINT]?: number;
    [SackItem.ENCHANTED_GHAST_TEAR]?: number;
    [SackItem.ENCHANTED_GLOWSTONE_DUST]?: number;
    [SackItem.ENCHANTED_GOLD]?: number;
    [SackItem.ENCHANTED_GUNPOWDER]?: number;
    [SackItem.ENCHANTED_ICE]?: number;
    [SackItem.ENCHANTED_INK_SACK]?: number;
    [SackItem.ENCHANTED_IRON]?: number;
    [SackItem.ENCHANTED_JUNGLE_WOOD]?: number;
    [SackItem.ENCHANTED_LAPIS_LAZULI]?: number;
    [SackItem.ENCHANTED_LEATHER]?: number;
    [SackItem.ENCHANTED_LILY_PAD]?: number;
    [SackItem.ENCHANTED_MAGMA_CREAM]?: number;
    [SackItem.ENCHANTED_MELON]?: number;
    [SackItem.ENCHANTED_MITHRIL]?: number;
    [SackItem.ENCHANTED_MUSHROOM]?: number;
    [SackItem.ENCHANTED_MUTTON]?: number;
    [SackItem.ENCHANTED_NETHERRACK]?: number;
    [SackItem.ENCHANTED_NETHER_WART]?: number;
    [SackItem.ENCHANTED_OAK_WOOD]?: number;
    [SackItem.ENCHANTED_OBSIDIAN]?: number;
    [SackItem.ENCHANTED_PACKED_ICE]?: number;
    [SackItem.ENCHANTED_PORK]?: number;
    [SackItem.ENCHANTED_POTATO]?: number;
    [SackItem.ENCHANTED_PRISMARINE_CRYSTALS]?: number;
    [SackItem.ENCHANTED_PRISMARINE_SHARD]?: number;
    [SackItem.ENCHANTED_PUFFERFISH]?: number;
    [SackItem.ENCHANTED_PUMPKIN]?: number;
    [SackItem.ENCHANTED_QUARTZ]?: number;
    [SackItem.ENCHANTED_RAW_CHICKEN]?: number;
    [SackItem.ENCHANTED_RAW_FISH]?: number;
    [SackItem.ENCHANTED_RAW_RABBIT]?: number;
    [SackItem.ENCHANTED_RAW_SALMON]?: number;
    [SackItem.ENCHANTED_REDSTONE]?: number;
    [SackItem.ENCHANTED_ROTTEN_FLESH]?: number;
    [SackItem.ENCHANTED_SAND]?: number;
    [SackItem.ENCHANTED_SEEDS]?: number;
    [SackItem.ENCHANTED_SLIMEBALL]?: number;
    [SackItem.ENCHANTED_SNOW_BLOCK]?: number;
    [SackItem.ENCHANTED_SPIDER_EYE]?: number;
    [SackItem.ENCHANTED_SPONGE]?: number;
    [SackItem.ENCHANTED_SPRUCE_WOOD]?: number;
    [SackItem.ENCHANTED_STRING]?: number;
    [SackItem.ENCHANTED_SUGAR]?: number;
    [SackItem.ENCHANTED_TITANIUM]?: number;
    [SackItem.ENDER_PEARL]?: number;
    [SackItem.END_STONE]?: number;
    [SackItem.FEATHER]?: number;
    [SackItem.FINE_AMBER_GEMSTONE]?: number;
    [SackItem.FINE_AMETHYST_GEMSTONE]?: number;
    [SackItem.FINE_JADE_GEMSTONE]?: number;
    [SackItem.FINE_JASPER_GEMSTONE]?: number;
    [SackItem.FINE_RUBY_GEMSTONE]?: number;
    [SackItem.FINE_SAPPHIRE_GEMSTONE]?: number;
    [SackItem.FINE_TOPAZ_GEMSTONE]?: number;
    [SackItem.FLAMING_HEART]?: number;
    [SackItem.FLAWED_AMBER_GEMSTONE]?: number;
    [SackItem.FLAWED_AMETHYST_GEMSTONE]?: number;
    [SackItem.FLAWED_JADE_GEMSTONE]?: number;
    [SackItem.FLAWED_JASPER_GEMSTONE]?: number;
    [SackItem.FLAWED_RUBY_GEMSTONE]?: number;
    [SackItem.FLAWED_SAPPHIRE_GEMSTONE]?: number;
    [SackItem.FLAWED_TOPAZ_GEMSTONE]?: number;
    [SackItem.FLAWLESS_AMBER_GEMSTONE]?: number;
    [SackItem.FLAWLESS_AMETHYST_GEMSTONE]?: number;
    [SackItem.FLAWLESS_JADE_GEMSTONE]?: number;
    [SackItem.FLAWLESS_JASPER_GEMSTONE]?: number;
    [SackItem.FLAWLESS_RUBY_GEMSTONE]?: number;
    [SackItem.FLAWLESS_SAPPHIRE_GEMSTONE]?: number;
    [SackItem.FLAWLESS_TOPAZ_GEMSTONE]?: number;
    [SackItem.GAZING_PEARL]?: number;
    [SackItem.GHAST_TEAR]?: number;
    [SackItem.GLOWSTONE_DUST]?: number;
    [SackItem.GOLD_INGOT]?: number;
    [SackItem.GRAVEL]?: number;
    [SackItem.GREEN_CANDY]?: number;
    [SackItem.GREEN_GIFT]?: number;
    [SackItem.GUNPOWDER]?: number;
    [SackItem.HALLOWED_SKULL]?: number;
    [SackItem.HARD_STONE]?: number;
    [SackItem.HORN_OF_TAURUS]?: number;
    [SackItem.HUNK_OF_BLUE_ICE]?: number;
    [SackItem.HUNK_OF_ICE]?: number;
    [SackItem.ICE]?: number;
    [SackItem.INFLATABLE_JERRY]?: number;
    [SackItem.INK_SACK]?: number;
    [SackItem.IRON_INGOT]?: number;
    [SackItem.JUNGLE_SAPLING]?: number;
    [SackItem.JUNGLE_WOOD]?: number;
    [SackItem.KADA_LEAD]?: number;
    [SackItem.LAPIS_LAZULI]?: number;
    [SackItem.LEATHER]?: number;
    [SackItem.LEATHER_CLOTH]?: number;
    [SackItem.LILY_PAD]?: number;
    [SackItem.LUMINO_FIBER]?: number;
    [SackItem.LUMP_OF_MAGMA]?: number;
    [SackItem.MAGMAFISH]?: number;
    [SackItem.MAGMAG]?: number;
    [SackItem.MAGMA_CHUNK]?: number;
    [SackItem.MAGMA_CREAM]?: number;
    [SackItem.MELON]?: number;
    [SackItem.MITHRIL]?: number;
    [SackItem.MOOGMA_PELT]?: number;
    [SackItem.MUSHROOM]?: number;
    [SackItem.MUTATED_BLAZE_ASHES]?: number;
    [SackItem.MUTTON]?: number;
    [SackItem.MYCELIUM]?: number;
    [SackItem.NETHERRACK]?: number;
    [SackItem.NETHER_QUARTZ]?: number;
    [SackItem.NETHER_WART]?: number;
    [SackItem.NULL_ATOM]?: number;
    [SackItem.NULL_SPHERE]?: number;
    [SackItem.OAK_SAPLING]?: number;
    [SackItem.OAK_WOOD]?: number;
    [SackItem.OBSIDIAN]?: number;
    [SackItem.ORB_OF_ENERGY]?: number;
    [SackItem.POTATO]?: number;
    [SackItem.PRISMARINE_CRYSTALS]?: number;
    [SackItem.PRISMARINE_SHARD]?: number;
    [SackItem.PUFFERFISH]?: number;
    [SackItem.PUMPKIN]?: number;
    [SackItem.PUMPKIN_GUTS]?: number;
    [SackItem.PURPLE_CANDY]?: number;
    [SackItem.PYROCLASTIC_SCALE]?: number;
    [SackItem.RAW_CHICKEN]?: number;
    [SackItem.RAW_FISH]?: number;
    [SackItem.RAW_PORKCHOP]?: number;
    [SackItem.RAW_RABBIT]?: number;
    [SackItem.RAW_SALMON]?: number;
    [SackItem.RAW_SOULFLOW]?: number;
    [SackItem.REDSTONE]?: number;
    [SackItem.RED_GIFT]?: number;
    [SackItem.RED_SAND]?: number;
    [SackItem.REVENANT_CATALYST]?: number;
    [SackItem.REVENANT_FLESH]?: number;
    [SackItem.ROTTEN_FLESH]?: number;
    [SackItem.ROUGH_AMBER_GEMSTONE]?: number;
    [SackItem.ROUGH_AMETHYST_GEMSTONE]?: number;
    [SackItem.ROUGH_JADE_GEMSTONE]?: number;
    [SackItem.ROUGH_JASPER_GEMSTONE]?: number;
    [SackItem.ROUGH_RUBY_GEMSTONE]?: number;
    [SackItem.ROUGH_SAPPHIRE_GEMSTONE]?: number;
    [SackItem.ROUGH_TOPAZ_GEMSTONE]?: number;
    [SackItem.SAND]?: number;
    [SackItem.SEEDS]?: number;
    [SackItem.SLIMEBALL]?: number;
    [SackItem.SNOWBALL]?: number;
    [SackItem.SOULFLOW]?: number;
    [SackItem.SPECTRE_DUST]?: number;
    [SackItem.SPELL_POWDER]?: number;
    [SackItem.SPIDER_CATALYST]?: number;
    [SackItem.SPIDER_EYE]?: number
    [SackItem.SPIRIT_LEAP]?: number;
    [SackItem.SPONGE]?: number;
    [SackItem.SPRUCE_SAPLING]?: number;
    [SackItem.SPRUCE_WOOD]?: number;
    [SackItem.STARFALL]?: number;
    [SackItem.STRING]?: number;
    [SackItem.SUGAR_CANE]?: number;
    [SackItem.SULPHUR]?: number;
    [SackItem.TARANTULA_WEB]?: number;
    [SackItem.TENTACLE_MEAT]?: number;
    [SackItem.TITANIUM]?: number;
    [SackItem.TRAP]?: number;
    [SackItem.TREASURITE]?: number;
    [SackItem.UNDEAD_CATALYST]?: number;
    [SackItem.WEREWOLF_SKIN]?: number;
    [SackItem.WHEAT]?: number;
    [SackItem.WHITE_GIFT]?: number;
    [SackItem.WITHER_SOUL]?: number;
    [SackItem.WOLF_TOOTH]?: number;
}
